Fix ts compile error for repl.ts
Error: "error TS2339: Property 'week' does not exist on type 'Context<{}>'."
This is because the Context now has the property 'chapter' instead of
'week'.