Remove misc.display, use console.log instead
The variable window is not defined, with ts-node, we get the error:

```
./toolchain/stdlib/misc.ts:16
window.display = display
^
ReferenceError: window is not defined
    at Object.<anonymous> (./slang/toolchain/stdlib/misc.ts:16:1)
    at Module._compile (module.js:660:30)
    at Module.m._compile
        (/usr/lib/node_modules/ts-node/src/index.ts:396:23)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts]
        (/usr/lib/node_modules/ts-node/src/index.ts:399:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

This variable was previously declared in the source-academy repository,
in `frontend/src/workspace/index.ts:  window.__REDUX_STORE__ = store`

/usr/lib/node_modules/ts-node/src/index.ts:253