Add dependency estree; set versions to match source-academy
Previously, running toolchain/index.ts with tsc would give the following
errors:

```
toolchain/constants.ts(1,21): error TS2307: Cannot find module 'estree'.
toolchain/interpreter-errors.ts(1,21):
    error TS2307: Cannot find module 'estree'.
toolchain/interpreter.ts(1,21):
    error TS2307: Cannot find module 'estree'.
toolchain/parser.ts(1,21): error TS2307: Cannot find module 'estree'.
toolchain/schedulers.ts(1,21):
    error TS2307: Cannot find module 'estree'.
toolchain/types.ts(1,21): error TS2307: Cannot find module 'estree'.
toolchain/utils/node.ts(4,21):
    error TS2307: Cannot find module 'estree'.
toolchain/utils/rttc.ts(1,21):
    error TS2307: Cannot find module 'estree'.
```

Also set the version requirements in package.json to match
source-academy, since this implementation was written for those
versions.