Fix compile error: cannot find name 'global'
toolchain/createContext.ts(5,48): error TS2552: Cannot find name
    'global'. Did you mean 'GLOBAL'?

It seems like this variable global, together with the file
createContext, was used for some JS framework (react?). Since we are
focusing on getting this thing up and running, I'm removing the entire
thing since I don't really know how otherwise to fix the compile error.

Can always look back into commit history and replace this change when we
eventually try to adapt it back to the main website. Might also not be
that bad since migration to cadet might have made some parts of
createContext redundant.