Fix compile error: 'ListVisualizer' ... not exist
toolchain/createContext.ts(111,16): error TS2339: Property
    'ListVisualizer' does not exist on type 'Window'.
toolchain/createContext.ts(112,44): error TS2339: Property
    'ListVisualizer' does not exist on type 'Window'.